name: CI - notification-service
on:
  push:
    branches: [main]
    paths:
      - "services/notification-service/**"
      - ".github/workflows/ci-notification-service.yaml"
      - ".github/workflows/ci-shared-template.yaml"
  pull_request:
    branches: [main]
    paths:
      - "services/notification-service/**"

concurrency:
  group: ci-notification-service-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  security-events: write
  attestations: write

jobs:
  ci:
    uses: ./.github/workflows/ci-shared-template.yaml
    with:
      service_name: notification-service
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
